# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignKeyModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='ManyToManyModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='OneToOneModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('model_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ModelA')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.AddField(
            model_name='manytomanymodel',
            name='model_a',
            field=models.ManyToManyField(to='app.ModelA'),
        ),
        migrations.AddField(
            model_name='foreignkeymodel',
            name='model_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ModelA'),
        ),
    ]
